# UAPI Header export list
header-y += ip6_tables.h
header-y += ip6t_hl.h
header-y += ip6t_log.h
header-y += ip6t_npt.h
header-y += ip6t_reject.h
header-y += ip6t_ah.h
header-y += ip6t_frag.h
header-y += ip6t_hl.h
header-y += ip6t_ipv6header.h
header-y += ip6t_mh.h
header-y += ip6t_opts.h
header-y += ip6t_rt.h
